In [2]:
import pandas as pd

In [44]:
df1=pd.read_csv("C:\\Users\\DELL\\Downloads\\22. messy_sales_data.csv")

In [45]:
df=df1.copy()

In [4]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [5]:
df.tail()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [6]:
df.shape

(106575, 15)

In [7]:
df.size

1598625

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106575 entries, 0 to 106574
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       106575 non-null  object
 1   CustomerID    106575 non-null  object
 2   CustomerName  106575 non-null  object
 3   City          104481 non-null  object
 4   Category      106575 non-null  object
 5   PaymentMode   103332 non-null  object
 6   Price         106575 non-null  object
 7   Quantity      106575 non-null  float64
 8   DiscountPct   106575 non-null  int64
 9   Rating        100129 non-null  float64
 10  OrderDate     102358 non-null  object
 11  CustomerAge   106575 non-null  float64
 12  Email         99176 non-null   object
 13  Phone         98117 non-null   object
 14  ReviewText    93200 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 12.2+ MB

In [11]:
df.describe()

            Quantity    DiscountPct         Rating    CustomerAge
count  106575.000000  106575.000000  100129.000000  106575.000000
mean        2.066817       9.382125       3.409874      39.678893
std         1.387769       9.176865       1.306731      19.263288
min        -5.000000       0.000000       0.500000       0.000000
25%         1.000000       0.000000       2.600000      28.000000
50%         2.000000      10.000000       3.300000      38.000000
75%         3.000000      20.000000       4.100000      47.000000
max         5.000000      25.000000       9.900000     150.000000

In [12]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='object')

In [13]:
df.dtypes

OrderID          object
CustomerID       object
CustomerName     object
City             object
Category         object
PaymentMode      object
Price            object
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate        object
CustomerAge     float64
Email            object
Phone            object
ReviewText       object
dtype: object

In [15]:
df.isnull().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [16]:
df.isnull().sum().sum()

np.int64(45232)

In [19]:
df.City

0         bangalore
1             DELHI
2           chennai
3           Jaipur
4           Amdavad
            ...
106570      chennai
106571         pune
106572        DELHI
106573    AHMEDABAD
106574      Chennai
Name: City, Length: 106575, dtype: object

In [24]:
df["City"].nunique()

56

In [22]:
df["Category"].nunique()

35

In [25]:
df["City"].value_counts()

City
hyderabad     2652
Jaipur        2651
JAIPUR        2635
LUCKNOW       2634
Jaipur        2631
 Hyderabad    2628
 Lucknow      2602
Hyderabad     2585
Lucknow       2575
jaipur        2569
HYDERABAD     2562
lucknow       2547
Ahmedabad     2134
Poona         2129
pune          2124
Amdavad       2110
Pune          2093
PUNE          2086
ahmedabad     2085
amdavad       2082
poona         2012
AHMEDABAD     1994
CALCUTTA      1833
madras        1816
Madras        1807
chennai       1805
Calcutta      1792
Chennai       1791
Kolkata       1755
KOLKATA       1753
kolkata       1739
CHENNAI       1728
calcutta      1672
MADRAS        1663
banglore      1557
bangalore     1549
New Delhi     1526
Bangalore     1517
NEW DELHI     1517
bengaluru     1488
BANGALORE     1481
new delhi     1473
Bengaluru     1462
DELHI         1456
delhi         1448
Delhi         1444
Banglore      1436
 Delhi        1396
BOMBAY        1362
Mumbai        1339
mumbai        1315
 Mumbai       1300
bombay        1298
mumbai        1296
MUMBAI        1281
Bombay        1266
Name: count, dtype: int64

In [27]:
df.duplicated().sum()

np.int64(1056)

In [28]:
df["col1"]=df["PaymentMode"]

In [30]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,col1
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,net_banking
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,Net Banking
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,Upi
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,COD
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,cc

In [32]:
df.sample()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,col1
42516,ORD5548,CUST03915,Peter Shenoy,Ahmedabad,grocery,Upi,1368.43,1.0,10,3.6,12-04-2024,18.0,peter.shenoy@rediffmail.com,9655251564,delivery was late,Upi

In [34]:
df.isnull().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
col1             3243
dtype: int64

In [35]:
df.DiscountPct.mean().round(3)*10

np.float64(93.82)

In [36]:
df.isna().mean().round(3)*100

OrderID          0.0
CustomerID       0.0
CustomerName     0.0
City             2.0
Category         0.0
PaymentMode      3.0
Price            0.0
Quantity         0.0
DiscountPct      0.0
Rating           6.0
OrderDate        4.0
CustomerAge      0.0
Email            6.9
Phone            7.9
ReviewText      12.5
col1             3.0
dtype: float64

In [37]:
df.["Quantity"].mean().round()*100

SyntaxError: invalid syntax (1178300744.py, line 1)

In [40]:
df[df["City"].isna()].head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,col1
44,ORD60845,CUST00989,LAKSH SAINI,NaN,Clothings,NaN,1312.67,4.0,10,2.6,12 Mar 2024,35.0,laksh.saini@gmail.com,9170359225,Not satisfied poor quality,NaN
110,ORD20288,CUST01667,BALVEER RAM,NaN,Books,dc,344.35,2.0,0,3.3,11/02/2024,25.0,balveer.ram@gmail.com,9538529304,Product as described,dc
130,ORD42875,CUST07659,Arjun Shukla,NaN,toys,cash on delivery,953.44,5.0,25,4.3,10 Dec 2024,47.0,arjun.shukla@gmail.com,9728243231,great service,cash on delivery
177,ORD14310,CUST07857,Lavanya Bhargava,NaN,furniture,upi,Rs.1575.61,1.0,0,3.4,09/18/2023,22.0,lavanya.bhargava@hotmail.com,+91-9177552059,Average experience,upi
195,ORD97450,CUST04620,Harrison Gala,NaN,Clothing,CREDIT CARD,873.31,1.0,5,1.2,2023-05-14,36.0,harrison.gala@hotmail.com,9163440026,Okayish product,CREDIT CARD

In [42]:
df[df["Category"].isna()].head()

Empty DataFrame
Columns: [OrderID, CustomerID, CustomerName, City, Category, PaymentMode, Price, Quantity, DiscountPct, Rating, OrderDate, CustomerAge, Email, Phone, ReviewText, col1]
Index: []

In [46]:
df["City"]=df["City"].fillna("Unknown")

In [48]:
df["City"].isnull().sum()

np.int64(0)

In [50]:
df["Price"].isnull().sum()

np.int64(0)

In [51]:
df["PaymentMode"].isnull().sum()

np.int64(3243)

In [55]:
df["PaymentMode"]=df["PaymentMode"].fillna(df["PaymentMode"].mode()[0])

In [58]:
df["PaymentMode"].isnull().sum()

np.int64(0)

In [59]:
df[df.duplicated(keep=False)]

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
81,ORD61902,CUST03914,Yash Sawhney,Calcutta,Book,UPI,1090.48,3.0,5,3.5,08/14/2023,27.0,yash.sawhney@gmail.com,9544764196,Okayish product
121,ORD19515,CUST03317,Balendra Lata,madras,beauty,Net Banking,"₹1,119.91",1.0,0,1.3,18-10-2023,37.0,balendra.lata@yahoo.com,+91-9312070442,delivery was late
130,ORD42875,CUST07659,Arjun Shukla,Unknown,toys,cash on delivery,953.44,5.0,25,4.3,10 Dec 2024,47.0,arjun.shukla@gmail.com,9728243231,great service
174,ORD97258,CUST04413,Jatin Borra,Pune,Toy,COD,₹738.54,3.0,25,4.2,2024-12-27,24.0,jatin.borra@hotmail.com,9164615469,Good product loved it
230,ORD88850,CUST05230,Falan Bumb,Lucknow,GROCERY,net banking,970.54,2.0,20,2.4,23/08/2023,50.0,falan.bumb@outlook.com,9680305954,Excellent!!! will buy again
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106224,ORD20702,CUST04842,Turvi Lad,kolkata,toys,UPI,905.00,3.0,15,4.5,04 Jan 2023,38.0,turvi.lad@gmail.com,9772902764,Excellent!!! will buy again
106266,ORD57327,CUST06398,Sai Misra,JAIPUR,BOOKS,Credit Card,933.80,1.0,0,1.9,NaN,21.0,sai.misra@outlook.com,9675353405,Amazing quality!!!
106399,ORD52908,CUST00065,Darsh Rau,LUCKNOW,ELECTRONICS,Upi,1131.14,2.0,5,3.0,06/05/2023,48.0,darsh.rau@gmail.com,9657689492,Not satisfied poor quality
106434,ORD17717,CUST00227,ZAYYAN SRIDHAR,CALCUTTA,furniture,cash on delivery,934.25,1.0,15,4.8,04/24/2024,38.0,zayyan.sridhar@rediffmail.com,9168130141,Not satisfied poor quality
106560,ORD68829,CUST01971,AARAV BOBAL,Bombay,Beauty,CREDIT CARD,-2040.44,4.0,15,3.9,2023-03-19,45.0,NaN,+91-9795734459,great service

In [60]:
df[df.duplicated(keep=False)].sort_values("OrderID").head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
12509,ORD10011,CUST05549,Dominic Nadig,Mumbai,grocery,Debit Card,986.17,2.0,10,1.1,09/23/2023,31.0,dominic.nadig@yahoo.com,9531043479,delivery was late
46621,ORD10011,CUST05549,Dominic Nadig,Mumbai,grocery,Debit Card,986.17,2.0,10,1.1,09/23/2023,31.0,dominic.nadig@yahoo.com,9531043479,delivery was late
54945,ORD100260,CUST08013,Krisha Mann,bangalore,Sport,CC,492.31,1.0,25,5.0,05/07/2023,36.0,krisha.mann@gmail.com,9240809583,Will not recommend
19142,ORD100260,CUST08013,Krisha Mann,bangalore,Sport,CC,492.31,1.0,25,5.0,05/07/2023,36.0,krisha.mann@gmail.com,9240809583,Will not recommend
77714,ORD100271,CUST01032,SIYA BORAH,Chennai,GROCERY,cc,4020.00,1.0,20,1.6,02/12/2023,18.0,siya.borah@rediffmail.com,9255516690,Not satisfied poor quality

In [61]:
df=df.drop_duplicates()

In [62]:
df.shape

(105519, 15)

In [64]:
df["OrderID"].duplicated().sum()

np.int64(519)

In [65]:
df["Category"].duplicated().sum()

np.int64(105484)

In [66]:
df["Email"].duplicated().sum()

np.int64(66168)

In [ ]:
dup_order_ids= df[df.["OrderID"].duplicated(keep=False)].sort_values("OrderID")

In [68]:
df["CustomerName"].unique()[1:35000:100]

array(['Siddharth Sha', 'Indali Kala', 'Chandresh Sarma', 'nikita kade',
       'Wahab Agarwal', 'Saksham Jaggi', 'Jacob Prabhu', 'Abeer Golla',
       'ayushman chander', '  Brijesh Mander  ', 'Rajata Gala',
       ' Shravya Kala', 'Priya Hora', 'Nidhi Sinha', 'vrishti sharaf',
       'Shivani Rajagopalan', '  Idika Mohanty  ', 'ADVIKA MITTAL',
       'Chavvi Gade', 'LILA REDDY', '  Fariq Sridhar  ',
       '  Damini Suri  ', 'Omya Karpe', 'Maanav De', 'Jasmit Mukherjee',
       'Rachana Bail', ' Theodore Krish', 'Triveni Pal',
       '  Sudiksha Nayar  ', '  Anika Warrior  ', '  Manan Nath  ',
       ' AASHI AHUJA', 'Yatin Ramesh', 'saumya dave', 'Alka Nagi',
       'Ojas Anne', 'Hiral Dey', 'yashica palla', ' Raksha Buch',
       'Bimala Dube', 'Eesha Singhal', 'SHAURYA KRISH',
       '  aradhana ratta  ', 'Panini Goda', 'Om Minhas', ' LUCKY PRAKASH',
       'Wyatt Tella', '  Pooja Ganguly  ', ' Shaurya Sarna',
       '  Chandresh Manda  ', 'Ekansh Balay', 'Ishwar Rattan',
       '  Chakradhar Venkataraman  ', '  Dakshesh Gill  ', 'Chasmum Sami',
       'ria tripathi', ' Krishna Sabharwal', ' RACHITA RAMAKRISHNAN',
       ' Chavvi Mani', '  Urvashi Sethi  ', '  Madhavi Morar  ',
       'Tripti Golla', 'ONI SUBRAMANIAM', 'sathvik bhavsar', 'Advay Tank',
       '  Madhavi Lanka  ', 'naksh goel', 'AARINI CHACKO',
       'Bhavani Bobal', '  Jatin Tak  ', 'Pavani Borra',
       'Eiravati Bansal', 'Tejas Krishnamurthy', 'Chameli Raman',
       'DAKSHESH CHEEMA', '  DAYAMAI NORI  ', 'QABIL ATWAL',
       'DARSH SOLANKI', 'Libni Sandal', '  JOSHUA SRINIVAS  ',
       '  Ekbal Garg  ', 'zaitra atwal', 'Jai Biswas', 'Avni Maharaj',
       'Vanya Srinivas', 'Rajeshri Chand', '  jagvi desai  ',
       '  Vasudha Tella  ', 'Ishwar Grewal', 'Netra Bhakta',
       'ekavir bhargava', ' Charles Murty', '  Sai Rout  ',
       'Sudiksha Nori', 'maanav khurana', 'Bimala Bath', '  Om Bhalla  ',
       'AGASTYA MISRA', 'Idika Brar', 'Laksh Sahota', ' Yasti Trivedi',
       'Daksh Ben', 'Gautami Mane', 'Wyatt Prasad', 'Radha Chaudhari',
       '  NAVEEN BHAVSAR  ', 'Jairaj Rana', ' Anjali Ahluwalia',
       '  DHRITI THAKUR  ', 'Maya Baria', '  Aarav Zacharia  ',
       '  Jackson Morar  ', 'Veer Srinivas', ' Vivaan Walla',
       'Yauvani Saxena', 'ekavir kari', 'pranav lanka', 'Anirudh Kata',
       'janaki agate', 'ANYA DHAR', 'Upma Menon', '  MAYA MUNSHI  ',
       'BHAVNA BHAT', 'Meera Walla', 'Sachi Luthra', ' Chandani Rout',
       'Vrinda Agrawal', 'Oni Mammen', 'Lopa Narasimhan',
       '  Jalsa Mitter  ', ' ranveer wadhwa', 'mohini srivastava',
       '  vihaan choudhury  ', '  Laban Balakrishnan  ',
       '  harish chokshi  ', 'Yuvraj Walia', 'YASH NAIR',
       ' advaith samra', '  hardik nayak  ', 'Dhriti Ramesh',
       ' Shaurya Kamdar', 'Baljiwan Bahri', ' Nikita Chander',
       'Balveer Koshy', 'Jalsa Saraf', ' Unni Deep', ' Daksha Gara',
       'Advika Patel', 'Ucchal Tiwari', 'KEYA KUMAR', '  Nakul Dhingra  ',
       ' LAKSHMI DE', '  Peter Tripathi  ', ' avi iyengar', 'Faras Ben',
       ' Riya Vohra', '  Sanaya Bains  ', 'Theodore Jain', 'LUCKY LUTHRA',
       'CHATRESH PALLA', '  MITALI WADHWA  ', 'VYANJANA AGARWAL',
       'Gunbir Kannan', 'arjun shroff', ' Leela Raval', 'nathan parmar',
       '  Irya Rattan  ', '  Pushti Chawla  ', 'ekapad walia',
       ' VAMAKSHI PARMER', 'kevin walla', '  ANYA DHAR  ', 'FARAS BRAR',
       '  Damyanti Reddy  ', ' ZARNA GANESH', '  Azad Magar  ',
       'Edhitha Mahajan', '  Abha Wadhwa  ', '  HARDIK SURI  ',
       ' Gautam Konda', 'SUDIKSHA DUGAL', 'YASHASVI BIR', '  Yug Sathe  ',
       '  Anay Sekhon  ', '  Samuel Panchal  ', 'THEODORE KUMAR',
       ' Praneel Madan', 'Robert Mani', 'aditya chaudhuri', 'ADVAY BEHL',
       '  Nisha Srinivas  ', '  Vincent Warrior  ', 'MOHAMMED BANSAL',
       'oni yohannan', 'Eta Vyas', '  DAKSHESH RAVAL  ',
       '  Hemangini Nigam  ', 'Ekapad Thakkar', 'ZASHIL DHINGRA',
       ' Lohit Rau', 'tarak sundaram', 'LOPA CHOKSHI', 'Mohammed Naik',
       'jyoti bose', 'GARIMA KADAKIA', 'Ladli Das', 'Tanay Sood',
       '  Jagat Butala  ', '  Indira Pandey  ', '  CHAITANYA SONI  ',
       'Krisha Prashad', 'gayathri mital', 'Harini Yohannan',
       'ekavir wable', 'Oni Andra', '  Faras Karpe  ', ' Yug Sunder',
       'veda chauhan', 'vyanjana amble', 'AYUSH BATRA', ' Aradhana Mane',
       'peter desai', 'ekbal kannan', 'IRYA KARPE', '  Chavvi Goel  ',
       '  LAJITA WALIA  ', '  anamika sachar  ', 'ekantika bains',
       '  kiaan lad  ', 'GOPAL BAWA', 'SAMESH MAHAJAN', 'Ishaan Iyengar',
       ' Jalsa Pillay', '  Ekanta Kala  ', ' Umang Manda',
       '  Vrinda Nadig  ', 'champak tripathi', 'Nirja Karan',
       '  chandresh kothari  ', 'Sanya Nanda', 'Anita Khurana',
       '  Gayathri Hari  ', 'Wridesh Chhabra', 'vrinda lanka',
       'Yashoda Prabhakar', 'GAURANGI DHAWAN', '  NEELIMA PARIKH  ',
       ' mohammed gupta', ' zayyan setty', 'BHAVNA KONDA', ' leela keer',
       '  Waida Chanda  ', ' Gautami Doctor', 'Noah Sachdeva',
       ' maya nigam', 'ISHA GOEL', '  chandani patla  ',
       '  Ojasvi Shah  ', ' Faras Sagar', 'QUINCY KARNIK', ' Jalsa Oza',
       'Kashvi Narula', '  Xiti Arya  ', 'HARRISON SANE', 'VARENYA DUA',
       'WRIDESH CHHABRA', ' Triveni Pal', ' advay tank',
       'GAURANGI MITTER', ' Anvi Naik', 'DEEPA BERA', ' Adya Lad',
       '  Yatin Rao  ', 'TANMAYI BABU', 'Edhitha Mani', 'SIMON SHANKER',
       '  hema venkataraman  ', '  Advaith Nori  ', ' Radhika Dayal',
       '  NEEL SRINIVAS  ', ' Avni Chaudhry', ' riya chaudry',
       'arin dass', ' Samaksh Chhabra', 'kashish chaudry',
       'FARHAN KAMDAR', '  Veda Guha  ', 'daksha tank', 'FREDERICK BAIL',
       ' Aadi Thaman', 'FALAK DUTTA', '  ROBERT MURTY  ',
       '  chandresh wali  ', 'VEER SUBRAMANIAM', '  BALVEER BHALLA  ',
       'samarth anne', 'suhani purohit', 'XITI PANDYA', 'RANBIR KUMAR',
       '  ODIKA NARULA  ', 'joshua zachariah', 'FIYAZ MURTHY',
       ' YASHODHARA SINGHAL', 'anusha anand', 'simon apte',
       'peter agarwal', '  Yahvi Mannan  ', ' Urishilla Kata',
       ' Amaira Sule', '  DIVYA PALLA  ', 'IJAYA KADAKIA',
       ' Lajita Biswas', ' YASH PUROHIT', ' Lucky Chaudhry',
       'abdul chand', ' Daksha Parekh', 'NIHARIKA KANT',
       '  harini gour  ', '  sachi mane  ', 'SAUMYA AHLUWALIA',
       '  Jagvi Hayre  ', ' Ekapad Palan', 'ria dalal',
       ' Balendra Deshpande', '  Idika Mani  ', ' yuvraj virk',
       'YAHVI BHATTI', '  Kala Uppal  ', '  saumya sandal  ',
       '  banjeet korpal  ', ' Osha Prasad', '  Ayushman Lalla  ',
       'omaja grover', '  Aarush Kala  ', 'LIAM NADIG', '  Ekaraj Raju  ',
       ' Max Narayan', ' Qarin Gokhale', 'jairaj tandon',
       '  Falan Warrior  ', 'WIDISHA PILLAI', 'aachal bhalla',
       '  Viraj Bhargava  ', '  eiravati bansal  ',
       '  Panini Srivastava  ', 'azad bhandari', ' Balveer Deshmukh',
       '  Anya Sangha  ', ' Lucky Sachar', 'VIHAAN CHOUDHURY'],
      dtype=object)

In [71]:
df["CustomerName"].str.strip().str.title()

0               Chaitanya Mane
1                Siddharth Sha
2         Nathaniel Chatterjee
3            Pranit Contractor
4           Hemang Chakraborty
                  ...
106570                  Max Om
106571            Charan Manne
106572             Isaiah Wali
106573          Ladli Nazareth
106574               Yatin Rao
Name: CustomerName, Length: 105519, dtype: object

In [72]:
df["New_Names"]=df["CustomerName"].str.strip().str.title()

C:\Users\DELL\AppData\Local\Temp\ipykernel_19772\577085235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["New_Names"]=df["CustomerName"].str.strip().str.title()

In [73]:
df["New_City"]=df["City"].str.strip().str.title()

C:\Users\DELL\AppData\Local\Temp\ipykernel_19772\2707740040.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["New_City"]=df["City"].str.strip().str.title()

In [74]:
df["New_City"]

0         Bangalore
1             Delhi
2           Chennai
3            Jaipur
4           Amdavad
            ...
106570      Chennai
106571         Pune
106572        Delhi
106573    Ahmedabad
106574      Chennai
Name: New_City, Length: 105519, dtype: object