In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\DELL\\Downloads\\22. messy_sales_data.csv")

In [4]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [5]:
df.tail()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [6]:
df.shape

(106575, 15)

In [7]:
df.size

1598625

In [9]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='object')

In [12]:
df.dtypes

OrderID          object
CustomerID       object
CustomerName     object
City             object
Category         object
PaymentMode      object
Price            object
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate        object
CustomerAge     float64
Email            object
Phone            object
ReviewText       object
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106575 entries, 0 to 106574
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       106575 non-null  object
 1   CustomerID    106575 non-null  object
 2   CustomerName  106575 non-null  object
 3   City          104481 non-null  object
 4   Category      106575 non-null  object
 5   PaymentMode   103332 non-null  object
 6   Price         106575 non-null  object
 7   Quantity      106575 non-null  float64
 8   DiscountPct   106575 non-null  int64
 9   Rating        100129 non-null  float64
 10  OrderDate     102358 non-null  object
 11  CustomerAge   106575 non-null  float64
 12  Email         99176 non-null   object
 13  Phone         98117 non-null   object
 14  ReviewText    93200 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 12.2+ MB

In [17]:
df.isnull().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [18]:
df.isnull().sum().sum()

np.int64(45232)

In [19]:
df.describe()

            Quantity    DiscountPct         Rating    CustomerAge
count  106575.000000  106575.000000  100129.000000  106575.000000
mean        2.066817       9.382125       3.409874      39.678893
std         1.387769       9.176865       1.306731      19.263288
min        -5.000000       0.000000       0.500000       0.000000
25%         1.000000       0.000000       2.600000      28.000000
50%         2.000000      10.000000       3.300000      38.000000
75%         3.000000      20.000000       4.100000      47.000000
max         5.000000      25.000000       9.900000     150.000000

In [20]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
OrderID,106575,105000,ORD17079,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerID,106575,9000,CUST01057,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerName,106575,37440,Charvi Dara,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,104481,56,hyderabad,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,106575,35,BEAUTY,4499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMode,103332,24,UPI,5184,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,106575,88579,966.86,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,106575.0,NaN,NaN,NaN,2.066817,1.387769,-5.0,1.0,2.0,3.0,5.0
DiscountPct,106575.0,NaN,NaN,NaN,9.382125,9.176865,0.0,0.0,10.0,20.0,25.0
Rating,100129.0,NaN,NaN,NaN,3.409874,1.306731,0.5,2.6,3.3,4.1,9.9
OrderDate,102358,3367,01/03/2024,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerAge,106575.0,NaN,NaN,NaN,39.678893,19.263288,0.0,28.0,38.0,47.0,150.0
Email,99176,39350,chakradhar.venkataraman@rediffmail.com,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Phone,98117,96653,9363299083,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ReviewText,93200,14,worst product ever received damaged item,6785,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.City

0         bangalore
1             DELHI
2           chennai
3           Jaipur
4           Amdavad
            ...
106570      chennai
106571         pune
106572        DELHI
106573    AHMEDABAD
106574      Chennai
Name: City, Length: 106575, dtype: object

In [23]:
df[["City", "Price", "Category"]]

             City       Price    Category
0       bangalore      904.48     Grocery
1           DELHI     1823.76      SPORTS
2         chennai      770.67  electronic
3         Jaipur      2028.06    Clothing
4         Amdavad      604.00   FURNITURE
...           ...         ...         ...
106570    chennai  Rs.1961.37   FURNITURE
106571       pune  Rs.1468.22        Toys
106572      DELHI      414.94   Furniture
106573  AHMEDABAD      916.52  electronic
106574    Chennai      891.46       Sport

[106575 rows x 3 columns]

In [24]:
df["City"].value_counts()

City
hyderabad     2652
Jaipur        2651
JAIPUR        2635
LUCKNOW       2634
Jaipur        2631
 Hyderabad    2628
 Lucknow      2602
Hyderabad     2585
Lucknow       2575
jaipur        2569
HYDERABAD     2562
lucknow       2547
Ahmedabad     2134
Poona         2129
pune          2124
Amdavad       2110
Pune          2093
PUNE          2086
ahmedabad     2085
amdavad       2082
poona         2012
AHMEDABAD     1994
CALCUTTA      1833
madras        1816
Madras        1807
chennai       1805
Calcutta      1792
Chennai       1791
Kolkata       1755
KOLKATA       1753
kolkata       1739
CHENNAI       1728
calcutta      1672
MADRAS        1663
banglore      1557
bangalore     1549
New Delhi     1526
Bangalore     1517
NEW DELHI     1517
bengaluru     1488
BANGALORE     1481
new delhi     1473
Bengaluru     1462
DELHI         1456
delhi         1448
Delhi         1444
Banglore      1436
 Delhi        1396
BOMBAY        1362
Mumbai        1339
mumbai        1315
 Mumbai       1300
bombay        1298
mumbai        1296
MUMBAI        1281
Bombay        1266
Name: count, dtype: int64